version: "3.8"
services:
  food-app:
    build: .
    container_name: "docker-app"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - api-food-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:123456@mongodb:27017/fooddb?authSource=admin
    env_file: des.env

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - api-food-network

volumes:
  mongodb_data: {}
networks:
  api-food-network:
    driver: bridge
