version: "3.8"
services:
  food-app:
    image: postechf57/pos-tech-g57-app-orders
    container_name: "docker-app"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - api-food-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/food_orders_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    # env_file: des.env

volumes:
  postgres_data: {}
networks:
  api-food-network:
    driver: bridge
