apiVersion: v1
kind: Service
metadata:
  name: api-food-orders-service
  namespace: orders
spec:
  type: ClusterIP
  selector:
    app: api-food-orders
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
