spring:
  application:
    name: api-food
  datasource:
    url: jdbc:postgresql://localhost:5432/fooddb
    username: your_postgres_user
    password: your_postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${ENVIRONMENT_PROFILE_VALUE:local}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
user: admin
pass: admin