spring:
  config:
    import: aws-secretsmanager:production/rds/postgres-v3
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:kakaka}
        secret-key: ${AWS_SECRET_KEY:kikiki}
  application:
    name: api-food
  datasource:
    url: jdbc:postgresql://${db_host}:5432/food_oders_db
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${ENVIRONMENT_PROFILE_VALUE:local}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
user: admin
pass: admin
